# Generated by Django 4.2.1 on 2023-05-23 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.car', verbose_name='car')),
                ('followers', models.ManyToManyField(related_name='following', to='account.user')),
            ],
        ),
    ]
