# Generated by Django 4.2.1 on 2023-05-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_style', models.CharField(blank=True, choices=[('S', 'Sedan'), ('HB', 'Hatchback'), ('SUV', 'SUV'), ('CO', 'Crossover'), ('C', 'Coupe'), ('Co', 'Convertible'), ('W', 'Wagon'), ('V', 'Van'), ('MV', 'Minivan'), ('P', 'Pickup'), ('T', 'Truck'), ('B', 'Bus'), ('Ot', 'Other')], max_length=14, null=True)),
                ('brand', models.CharField(choices=[('Acura', 'Acura'), ('Alfa Romeo', 'Alfa Romeo'), ('Aston Martin', 'Aston Martin'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Bugatti', 'Bugatti'), ('Buick', 'Buick'), ('Cadillac', 'Cadillac'), ('Chevrolet', 'Chevrolet'), ('Chrysler', 'Chrysler'), ('Citroen', 'Citroen'), ('Dodge', 'Dodge'), ('Ferrari', 'Ferrari'), ('Fiat', 'Fiat'), ('Ford', 'Ford'), ('Geely', 'Geely'), ('General Motors', 'General Motors'), ('GMC', 'GMC'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Infiniti', 'Infiniti'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('Kia', 'Kia'), ('Koenigsegg', 'Koenigsegg'), ('Lamborghini', 'Lamborghini'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Lincoln', 'Lincoln'), ('Lotus', 'Lotus'), ('Maserati', 'Maserati'), ('Mazda', 'Mazda'), ('McLaren', 'McLaren'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Mini', 'Mini'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Pagani', 'Pagani'), ('Peugeot', 'Peugeot'), ('Porsche', 'Porsche'), ('Ram', 'Ram'), ('Renault', 'Renault'), ('Rolls Royce', 'Rolls Royce'), ('Saab', 'Saab'), ('Subaru', 'Subaru'), ('Suzuki', 'Suzuki'), ('Tesla', 'Tesla'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('Ot', 'Other')], max_length=53)),
                ('model', models.CharField(blank=True, choices=[], max_length=50, null=True)),
                ('life_style', models.CharField(blank=True, choices=[('F', 'Family'), ('S', 'Sport'), ('L', 'Luxury'), ('C', 'Classic'), ('E', 'Envoirment'), ('Ot', 'Other')], max_length=7, null=True)),
                ('year', models.CharField(blank=True, choices=[], max_length=50, null=True)),
                ('fule_type', models.CharField(blank=True, choices=[('G', 'Gasoline'), ('D', 'Diesel'), ('E', 'Electric'), ('H', 'Hybrid'), ('Ot', 'Other')], max_length=6, null=True)),
                ('color', models.CharField(blank=True, choices=[('B', 'Black'), ('W', 'White'), ('S', 'Silver'), ('G', 'Gray'), ('R', 'Red'), ('B', 'Blue'), ('Y', 'Yellow'), ('O', 'Orange'), ('P', 'Purple'), ('Ot', 'Other')], max_length=11, null=True)),
                ('price', models.FloatField(blank=True, max_length=50, null=True)),
                ('mileage', models.FloatField(blank=True, max_length=50, null=True)),
                ('transmission', models.CharField(blank=True, choices=[('A', 'Automatic'), ('M', 'Manual'), ('Ot', 'Other')], max_length=4, null=True)),
                ('body_status', models.CharField(blank=True, choices=[('E', 'Excellent'), ('G', 'Good'), ('A', 'Average'), ('B', 'Bad'), ('Ot', 'Other')], max_length=6, null=True)),
                ('customs_case', models.CharField(blank=True, choices=[('C', 'Cleared'), ('N', 'Not Cleared'), ('Ot', 'Other')], max_length=4, null=True)),
                ('horsepower', models.IntegerField(blank=True, null=True)),
                ('engine_description', models.CharField(blank=True, max_length=50, null=True)),
                ('engine_capacity', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('safety_and_technology', models.CharField(blank=True, max_length=50, null=True)),
                ('front_style_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('back_style_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('front_style_description', models.CharField(blank=True, max_length=50, null=True)),
                ('back_style_description', models.CharField(blank=True, max_length=50, null=True)),
                ('strengh_points', models.CharField(blank=True, max_length=50, null=True)),
                ('weaknesses', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
